workflows:
  native-ios-ui-workflow:
    name: Native iOS UI Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          cd example && flutter packages pub get
      - name: Create iOS directories if needed
        script: |
          mkdir -p ios
          mkdir -p example/ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install || true
          cd ../example/ios
          pod install || true
      - name: Build iOS example
        script: |
          cd example
          flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/ipa/**/*.ipa
      - flutter_drive.log
