name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving native_ios_ui!
        
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm frustrated when...
    validations:
      required: false
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternatively...
    validations:
      required: false
      
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your use case and how this feature would help you.
      placeholder: I need this because...
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information...
