# GitHub Actions workflow specifically for iOS
name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Check iOS directories
        run: |
          mkdir -p ios
          mkdir -p example/ios
      
      - name: Install pod dependencies
        run: |
          cd ios
          pod install || true
          cd ../example/ios
          pod install || true
      
      - name: Run tests
        run: flutter test
      
      - name: Build iOS example (debug)
        run: |
          cd example
          flutter build ios --debug --no-codesign
